name: Multi-Job Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build      # This job runs after 'build'
    steps:
      - name: Run Tests
        run: echo "Running tests..."
